version: '3'
services:
  event-service:
    build: ./event-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - user-service
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongodb:27017/event-service
      - RABBITMQ_URI=amqp://rabbitmq:5672

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user-service
      - RABBITMQ_URI=amqp://rabbitmq:5672

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ Management UI

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"   # Public access to your services
      - "8443:8443"   # Secure public access to your services
      - "8001:8001"   # Kong Admin API (non-SSL)
      - "8444:8444"   # Kong Admin API (SSL)
    depends_on:
      - event-service
      - user-service
